<a href="https://colab.research.google.com/github/SarahSchilling618/project-4/blob/main/working_file.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!pip install psycopg2-binary

Requirement already satisfied: psycopg2-binary in c:\users\micha\anaconda3\envs\dev\lib\site-packages (2.9.9)

In [2]:
import psycopg2
from psycopg2 import sql
import pandas as pd

In [4]:
db_params = {
    'dbname': 'project4',
    'user': 'postgres',
    'password': 'postgres',
    'host': 'localhost',
    'port': '5432'
}

# Establish the connection
conn = psycopg2.connect(**db_params)
cursor = conn.cursor()

In [5]:
cursor.execute('SELECT * FROM dementia LIMIT 5;')
rows = cursor.fetchall()

In [6]:
colnames = [desc[0] for desc in cursor.description]
df = pd.DataFrame(rows, columns=colnames)

In [7]:
df

,Diabetic,AlcoholLevel,HeartRate,BloodOxygenLevel,BodyTemperature,Weight,MRI_Delay,Prescription,Dosage_in_mg,Age,...,Smoking_Status,APOE_4,Physical_Activity,Depression_Status,Cognitive_Test_Scores,Medication_History,Nutrition_Diet,Sleep_Quality,Chronic_Health_Conditions,Dementia
0,1,0.084974,98,96.230743,36.224852,57.563978,36.421028,None,NaN,60,...,Current Smoker,Negative,Sedentary,No,10,No,Low-Carb Diet,Poor,Diabetes,0
1,0,0.016973,78,93.032122,36.183874,56.832335,31.157633,Galantamine,12.0,61,...,Former Smoker,Positive,Moderate Activity,No,1,Yes,Low-Carb Diet,Poor,Heart Disease,1
2,0,0.009000,89,93.566504,37.326321,59.759066,37.640435,None,NaN,69,...,Former Smoker,Negative,Moderate Activity,No,8,No,Mediterranean Diet,Poor,Heart Disease,0
3,0,0.086437,60,93.906510,37.030620,58.266471,50.673992,Donepezil,23.0,78,...,Never Smoked,Negative,Mild Activity,Yes,5,Yes,Balanced Diet,Poor,Hypertension,1
4,1,0.150747,67,97.508994,36.062121,67.705027,27.810601,Memantine,20.0,77,...,Never Smoked,Positive,Mild Activity,No,0,Yes,Low-Carb Diet,Good,Diabetes,1

In [26]:
conn.close()

In [29]:
conn = psycopg2.connect(**db_params)
cursor = conn.cursor()

distinct_values_query = '''
    SELECT DISTINCT "Smoking_Status"
    FROM dementia;
'''
cursor.execute(distinct_values_query)
distinct_values = cursor.fetchall()

print("Distinct values in the Smoking_Status column:")
for value in distinct_values:
    print(value[0])

Distinct values in the Smoking_Status column:
Never Smoked
Current Smoker
Former Smoker

In [30]:
update_query = '''
    UPDATE dementia
    SET "Smoking_Status" = CASE
        WHEN "Smoking_Status" = 'Never Smoked' THEN '0'
        WHEN "Smoking_Status" = 'Former Smoker' THEN '1'
        WHEN "Smoking_Status" = 'Current Smoker' THEN '2'
        ELSE "Smoking_Status"
    END;
'''
cursor.execute(update_query)

In [32]:
conn.commit()

In [35]:
update_query = '''
    UPDATE dementia
    SET "APOE_4" = CASE
        WHEN "APOE_4" = 'Negative' THEN '0'
        WHEN "APOE_4" = 'Positive' THEN '1'
        ELSE "APOE_4"
    END;
'''
cursor.execute(update_query)

conn.commit()

In [37]:
physical_activity_check = '''
    SELECT DISTINCT "Physical_Activity"
    FROM dementia;
'''
cursor.execute(physical_activity_check)
distinct_pa = cursor.fetchall()

for value in distinct_pa:
    print(value[0])

Mild Activity
Sedentary
Moderate Activity

In [38]:
update_query = '''
    UPDATE dementia
    SET "Physical_Activity" = CASE
        WHEN "Physical_Activity" = 'Sedentary' THEN '0'
        WHEN "Physical_Activity" = 'Mild Activity' THEN '1'
        WHEN "Physical_Activity" = 'Moderate Activity' THEN '2'
    END;
'''
cursor.execute(update_query)

conn.commit()

In [39]:
update_query = '''
    UPDATE dementia
    SET "Depression_Status" = CASE
        WHEN "Depression_Status" = 'No' THEN '0'
        WHEN "Depression_Status" = 'Yes' THEN '1'
    END;
'''
cursor.execute(update_query)

conn.commit()

In [40]:
update_query = '''
    UPDATE dementia
    SET "Medication_History" = CASE
        WHEN "Medication_History" = 'No' THEN '0'
        WHEN "Medication_History" = 'Yes' THEN '1'
    END;
'''
cursor.execute(update_query)

conn.commit()

In [41]:
diet_check = '''
    SELECT DISTINCT "Nutrition_Diet"
    FROM dementia;
'''
cursor.execute(diet_check)
distinct_diet = cursor.fetchall()

for value in distinct_diet:
    print(value[0])

Low-Carb Diet
Mediterranean Diet
Balanced Diet

In [42]:
update_query = '''
    UPDATE dementia
    SET "Nutrition_Diet" = CASE
        WHEN "Nutrition_Diet" = 'Low-Carb Diet' THEN '0'
        WHEN "Nutrition_Diet" = 'Mediterranean Diet' THEN '1'
        WHEN "Nutrition_Diet" = 'Balanced Diet' THEN '2'
    END;
'''
cursor.execute(update_query)

conn.commit()

In [43]:
update_query = '''
    UPDATE dementia
    SET "Sleep_Quality" = CASE
        WHEN "Sleep_Quality" = 'Poor' THEN '0'
        WHEN "Sleep_Quality" = 'Good' THEN '1'
    END;
'''
cursor.execute(update_query)

conn.commit()

In [44]:
health_check = '''
    SELECT DISTINCT "Chronic_Health_Conditions"
    FROM dementia;
'''
cursor.execute(health_check)
distinct_health = cursor.fetchall()

for value in distinct_health:
    print(value[0])

Hypertension
None
Diabetes
Heart Disease

In [45]:
update_query = '''
    UPDATE dementia
    SET "Chronic_Health_Conditions" = CASE
        WHEN "Chronic_Health_Conditions" = 'None' THEN '0'
        WHEN "Chronic_Health_Conditions" = 'Hypertension' THEN '1'
        WHEN "Chronic_Health_Conditions" = 'Diabetes' THEN '2'
        WHEN "Chronic_Health_Conditions" = 'Heart Disease' THEN '3'
    END;
'''
cursor.execute(update_query)

conn.commit()

In [47]:
cursor.execute('SELECT * FROM dementia LIMIT 5;')
rows = cursor.fetchall()

colnames2 = [desc[0] for desc in cursor.description]
df_clean = pd.DataFrame(rows, columns=colnames2)

df_clean

,Diabetic,AlcoholLevel,HeartRate,BloodOxygenLevel,BodyTemperature,Weight,MRI_Delay,Prescription,Dosage_in_mg,Age,...,Smoking_Status,APOE_4,Physical_Activity,Depression_Status,Cognitive_Test_Scores,Medication_History,Nutrition_Diet,Sleep_Quality,Chronic_Health_Conditions,Dementia
0,1,0.132931,84,97.441080,36.116462,96.742030,20.762411,None,NaN,87,...,1,1,2,0,9,0,1,1,2,0
1,1,0.048213,99,98.041581,36.367684,90.665241,36.317350,None,NaN,76,...,0,0,0,0,9,1,1,1,2,0
2,0,0.141819,88,97.463829,37.106843,62.508289,43.944018,Galantamine,8.0,62,...,1,1,1,1,2,0,2,0,1,1
3,0,0.025385,84,93.751975,37.056758,78.476648,12.383425,None,NaN,86,...,1,0,1,0,9,1,2,1,0,0
4,1,0.198418,69,99.824699,36.733106,56.909268,55.072191,Galantamine,12.0,61,...,0,1,0,1,6,1,1,0,2,1